import { describe, expect, it } from "vitest";
import {
  ACCESS_ACTOR_TYPES,
  ACCESS_AUTHORIZATION_TYPES,
  ACCESS_OUTCOMES,
  ACCESS_REASON_CODES,
  ACCESS_SOURCE_TYPES,
  ACCESS_SURFACES,
  ARTIFACT_EDITION_STATUSES,
  ARTIFACT_CARRY_FORWARD_MAX_SELECTIONS,
  ARTIFACT_REVISION_TRIGGERS,
  CAPTURE_ASSET_TYPES,
  CAPTURE_ASSET_PURGE_OPERATION_STATUSES,
  CAPTURE_ASSET_STATUSES,
  CAPTURE_EVENT_TYPES,
  CAPTURE_SESSION_SOURCE_TYPES,
  CAPTURE_SESSION_STATUSES,
  DEMO_HOTSPOT_TYPES,
  DEPLOYMENT_MODES,
  FILE_STORAGE_PROVIDERS,
  GUIDE_ANNOTATION_TYPES,
  GUIDE_BLOCK_PLACEMENTS,
  GUIDE_BLOCK_TYPES,
  GUIDE_CREATABLE_BLOCK_TYPES,
  ONBOARDING_MODES,
  ORGANIZATION_INVITE_STATUSES,
  ORGANIZATION_MEMBER_STATUSES,
  ORGANIZATION_ROLES,
  PROJECT_STATUSES,
  PROJECT_ACCESS_SOURCES,
  PROJECT_ACTIVITY_CATEGORIES,
  PROJECT_LIST_PURPOSES,
  PROJECT_MEMBERSHIP_STATUSES,
  PROJECT_ROLES,
  PROJECT_VERSION_RESOLUTION_KINDS,
  PROJECT_VERSION_STATUSES,
  DOCUMENTATION_BLOCK_KINDS,
  DOCUMENTATION_COMMENT_STATES,
  DOCUMENTATION_NAVIGATION_KINDS,
  DOCUMENTATION_ROUTING_OUTCOMES,
  DOCUMENTATION_PACKAGE_FORMAT,
  DOCUMENTATION_PACKAGE_FORMAT_VERSION,
  DOCUMENTATION_PACKAGE_PROFILES,
  DOCUMENTATION_IMPORT_ISSUE_CODES,
  DOCUMENTATION_IMPORT_ISSUES_MAX,
  DOCUMENTATION_MARKDOWN_UPLOAD_MAX_BYTES,
  DOCUMENTATION_PACKAGE_UPLOAD_MAX_BYTES,
  DOCUMENTATION_PACKAGE_EXPANDED_MAX_BYTES,
  DOCUMENTATION_LIFECYCLE_STATUSES,
  DOCUMENTATION_EFFECTIVE_STATUSES,
  DOCUMENTATION_REVISION_TRIGGERS,
  DOCUMENTATION_CARRY_FORWARD_MAX_SELECTIONS,
  DOCUMENTATION_CARRY_FORWARD_PAGES_MAX,
  DOCUMENTATION_CARRY_FORWARD_SNIPPETS_MAX,
  DOCUMENTATION_CARRY_FORWARD_CONTENT_NODES_MAX,
  DOCUMENTATION_CARRY_FORWARD_PROTECTED_REFERENCES_MAX,
  DOCUMENTATION_CARRY_FORWARD_SAVED_TEXT_MAX_BYTES,
  DOCUMENTATION_REVIEW_POLICY_MODES,
  DOCUMENTATION_REVIEW_REQUEST_STATUSES,
  DOCUMENTATION_REVIEW_EFFECTIVE_STATUSES,
  DOCUMENTATION_REVIEW_DECISIONS,
  DOCUMENTATION_PUBLICATION_REVIEW_OUTCOMES,
  DOCUMENTATION_REVIEW_INBOX_STATUSES,
  DOCUMENTATION_REVIEW_NOTIFICATION_TYPES,
  DOCUMENTATION_REVIEWERS_MAX,
  DOCUMENTATION_REVIEW_MAINTAINERS_MAX,
  DOCUMENTATION_REVIEW_REASON_MAX,
  DOCUMENTATION_REVIEW_INBOX_PAGE_MAX,
  DOCUMENTATION_REVIEW_REQUESTS_PER_EDITION_HARD_MAX,
  PUBLISH_RESOURCE_FAMILIES,
  PUBLISH_ARTIFACT_TYPES,
  PUBLISH_LINK_ENTRY_MAX,
  PUBLISH_LINK_NAME_MAX_LENGTH,
  PUBLISH_LINK_STATUSES,
  PUBLISH_VISIBILITIES,
} from "./index";

const exported_constant_sets = {
  ACCESS_ACTOR_TYPES,
  ACCESS_AUTHORIZATION_TYPES,
  ACCESS_OUTCOMES,
  ACCESS_REASON_CODES,
  ACCESS_SOURCE_TYPES,
  ACCESS_SURFACES,
  ARTIFACT_EDITION_STATUSES,
  ARTIFACT_REVISION_TRIGGERS,
  CAPTURE_ASSET_PURGE_OPERATION_STATUSES,
  CAPTURE_ASSET_STATUSES,
  CAPTURE_SESSION_STATUSES,
  CAPTURE_SESSION_SOURCE_TYPES,
  CAPTURE_EVENT_TYPES,
  CAPTURE_ASSET_TYPES,
  FILE_STORAGE_PROVIDERS,
  GUIDE_BLOCK_TYPES,
  GUIDE_CREATABLE_BLOCK_TYPES,
  GUIDE_BLOCK_PLACEMENTS,
  GUIDE_ANNOTATION_TYPES,
  DEMO_HOTSPOT_TYPES,
  PUBLISH_ARTIFACT_TYPES,
  PUBLISH_VISIBILITIES,
  PUBLISH_LINK_STATUSES,
  ORGANIZATION_ROLES,
  ORGANIZATION_INVITE_STATUSES,
  ORGANIZATION_MEMBER_STATUSES,
  PROJECT_STATUSES,
  PROJECT_ACCESS_SOURCES,
  PROJECT_ACTIVITY_CATEGORIES,
  PROJECT_LIST_PURPOSES,
  PROJECT_MEMBERSHIP_STATUSES,
  PROJECT_ROLES,
  PROJECT_VERSION_RESOLUTION_KINDS,
  PROJECT_VERSION_STATUSES,
  DOCUMENTATION_BLOCK_KINDS,
  DOCUMENTATION_COMMENT_STATES,
  DOCUMENTATION_NAVIGATION_KINDS,
  DOCUMENTATION_ROUTING_OUTCOMES,
  DOCUMENTATION_LIFECYCLE_STATUSES,
  DOCUMENTATION_EFFECTIVE_STATUSES,
  DOCUMENTATION_REVISION_TRIGGERS,
  PUBLISH_RESOURCE_FAMILIES,
  DEPLOYMENT_MODES,
  ONBOARDING_MODES,
} as const;

describe("@repo/constants", () => {
  it("exports unique tuple values for every constants set", () => {
    for (const [name, values] of Object.entries(exported_constant_sets)) {
      expect(
        new Set(values),
        `${name} should not contain duplicate values`,
      ).toHaveLength(values.length);
    }
  });

  it("keeps guide creatable block types inside the full guide block type set", () => {
    for (const block_type of GUIDE_CREATABLE_BLOCK_TYPES) {
      expect(GUIDE_BLOCK_TYPES).toContain(block_type);
    }
  });

  it("exports the bounded multi-version publish link limits", () => {
    expect(PUBLISH_LINK_ENTRY_MAX).toBe(50);
    expect(PUBLISH_LINK_NAME_MAX_LENGTH).toBe(120);
  });

  it("keeps Documentation and Artifact publication families explicit", () => {
    expect(PUBLISH_RESOURCE_FAMILIES).toEqual([
      "artifact",
      "documentation_site",
    ]);
    expect(PUBLISH_ARTIFACT_TYPES).toEqual(["guide", "interactive_demo"]);
    expect(DOCUMENTATION_BLOCK_KINDS).toContain("api_reference");
  });

  it("exports the frozen Documentation portability identity and safety ceilings", () => {
    expect(DOCUMENTATION_PACKAGE_FORMAT).toBe("ossie.documentation-site");
    expect(DOCUMENTATION_PACKAGE_FORMAT_VERSION).toBe(1);
    expect(DOCUMENTATION_PACKAGE_PROFILES).toEqual([
      "roundtrip",
      "markdown-folder",
    ]);
    expect(DOCUMENTATION_IMPORT_ISSUE_CODES).toContain(
      "archive_integrity_mismatch",
    );
    expect(DOCUMENTATION_IMPORT_ISSUES_MAX).toBe(500);
    expect(DOCUMENTATION_MARKDOWN_UPLOAD_MAX_BYTES).toBe(4 * 1024 * 1024);
    expect(DOCUMENTATION_PACKAGE_UPLOAD_MAX_BYTES).toBe(32 * 1024 * 1024);
    expect(DOCUMENTATION_PACKAGE_EXPANDED_MAX_BYTES).toBe(128 * 1024 * 1024);
  });

  it("exports the accepted Documentation lifecycle and carry-forward boundaries", () => {
    expect(DOCUMENTATION_LIFECYCLE_STATUSES).toEqual(["active", "archived"]);
    expect(DOCUMENTATION_EFFECTIVE_STATUSES).toEqual([
      "active",
      "read_only",
      "archived",
    ]);
    expect(DOCUMENTATION_REVISION_TRIGGERS).toEqual([
      "manual_checkpoint",
      "publication",
      "carry_forward",
    ]);
    expect(DOCUMENTATION_CARRY_FORWARD_MAX_SELECTIONS).toBe(10);
    expect(DOCUMENTATION_CARRY_FORWARD_PAGES_MAX).toBe(5_000);
    expect(DOCUMENTATION_CARRY_FORWARD_SNIPPETS_MAX).toBe(5_000);
    expect(DOCUMENTATION_CARRY_FORWARD_CONTENT_NODES_MAX).toBe(250_000);
    expect(DOCUMENTATION_CARRY_FORWARD_PROTECTED_REFERENCES_MAX).toBe(10_000);
    expect(DOCUMENTATION_CARRY_FORWARD_SAVED_TEXT_MAX_BYTES).toBe(
      256 * 1024 * 1024,
    );
    expect(DOCUMENTATION_REVIEW_POLICY_MODES).toEqual([
      "optional",
      "approval_required",
    ]);
    expect(DOCUMENTATION_REVIEW_REQUEST_STATUSES).toEqual([
      "open",
      "approved",
      "rejected",
      "canceled",
      "superseded",
    ]);
    expect(DOCUMENTATION_REVIEW_EFFECTIVE_STATUSES).toEqual([
      "open",
      "approved",
      "rejected",
      "canceled",
      "superseded",
      "invalidated",
    ]);
    expect(DOCUMENTATION_REVIEW_DECISIONS).toEqual(["approve", "reject"]);
    expect(DOCUMENTATION_PUBLICATION_REVIEW_OUTCOMES).toEqual([
      "not_required",
      "approved",
      "overridden",
    ]);
    expect(DOCUMENTATION_REVIEW_INBOX_STATUSES).toEqual(["unread", "read"]);
    expect(DOCUMENTATION_REVIEW_NOTIFICATION_TYPES).toHaveLength(6);
    expect(DOCUMENTATION_REVIEWERS_MAX).toBe(10);
    expect(DOCUMENTATION_REVIEW_MAINTAINERS_MAX).toBe(20);
    expect(DOCUMENTATION_REVIEW_REASON_MAX).toBe(1_000);
    expect(DOCUMENTATION_REVIEW_INBOX_PAGE_MAX).toBe(50);
    expect(DOCUMENTATION_REVIEW_REQUESTS_PER_EDITION_HARD_MAX).toBe(10_000);
  });

  it("keeps public instance mode defaults representable by exported constants", () => {
    expect(DEPLOYMENT_MODES).toContain("self_hosted");
    expect(DEPLOYMENT_MODES).toContain("hosted");
    expect(ONBOARDING_MODES).toContain("first_run_setup");
    expect(ONBOARDING_MODES).toContain("signup");
  });

  it("exports the accepted bounded Revision and protected Asset constants", () => {
    expect(ARTIFACT_REVISION_TRIGGERS).toEqual([
      "manual_checkpoint",
      "publication",
      "carry_forward",
    ]);
    expect(ARTIFACT_CARRY_FORWARD_MAX_SELECTIONS).toBe(50);
    expect(CAPTURE_ASSET_STATUSES).toEqual(["active", "archived"]);
    expect(CAPTURE_ASSET_PURGE_OPERATION_STATUSES).toEqual([
      "pending",
      "failed",
      "completed",
    ]);
  });
});
